### ISSUE TITLE
Any Edits made in the App need to be set as provisional

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches-mobile#137]
**User Story**

All Edits made/proposed in the mobile environment should be saved as provisional to be reviewed and approved from a full Arches environment, regardless of user permissions. 

Edits made in a mobile may be subject to stale data:
- Sync happened 1 month before saving back to arches
- Mobile keyboards are subject to typos and autocorrect issues

**Ticket Background**
*   Sponsored by: Getty Conservation Institute
*   Suggested by: @jmunowitch

**Comment by dwuthrich** [comment]
@jmunowitch @chiatt Edits made by mobile app users who are members of the Resource Reviewer group (aka the QA/QC group) should be accepted without provisional status, as is the case in the web client.

**Comment by chiatt** [comment]
@dwuthrich Assuming that the user experience on a mobile device is the same for both reviewers and provisional editors, it makes sense to save all mobile edits to the provisionaledits tile property because the provisionaledits property allows a way to track the editor's id within the tile once the data arrives in Couch. This information is needed for the tile edit history in Arches. Without it we wouldn't know who made the most recent edit. During sync to postgres, the logic that reconciles couch and postgres can make the determination whether an edit should be saved directly to the authoritative `data` property based on the editor's id in the provisional edit.

**Comment by dwuthrich** [comment]
Cyrus,

Thanks for the explanation.  Makes sense!

**Comment by jmunowitch** [comment]
The `timestamp` property on `provisionaledits` is not being set when it comes from mobile.

**Comment by jmunowitch** [comment]
Reviewed and looks good.

**Comment by jmunowitch** [comment]
Resurrecting this issue: 
New Tiles created in the mobile app save data as both provisionaledits and as authoritative data.

**Comment by chiatt** [comment]
@jmunowitch That issue is now addressed by #171
