### ISSUE TITLE
Download MBtiles file during project init for mobile app

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-mobile#40]

**Comment by chiatt** [comment]
The mbtiles database downloads and opens for me on iOS, but the map does not display. I am also not seeing resource instances listed when I select a resource type from the resource type list. I suspect that the map isn't loading because there is no resource/tile data loading in the ios emulator (as it does in the browser) possibly?

**Comment by chiatt** [comment]
This is working for me both on an android device as well as in an iOS emulator.
